### ISSUE TITLE
websnark.js src references

### ISSUE THREAD

**Issue by holgerd77** [iden3/websnark#1]
Didn't have a very long look, so feel free to directly close if not an issue, thought it might make sense to mention though:

The ``build/websnark.js`` file has ``./src/`` folder references in the code - e.g. [here](https://github.com/iden3/websnark/blob/master/build/websnark.js#L31). Is this intended?

**Comment by jbaylina** [comment]
This file is automatically generated file..

This should be optimized, checked what is generated and uglify it later to get a better size....
